/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserInterface.java
 *
 * Created on Dec 1, 2013, 8:38:52 PM
 */

package its;

/**
 *
 * @author Rogue
 */
import java.io.*;

public class UserInterface extends javax.swing.JFrame {

    int MAX = 10;
    int member = 0;
    User[] user = new User[MAX];
    Login login;
    
    /** Creates new form UserInterface */
    public UserInterface() {
        initComponents();
        registerFrame.setBounds( (0), (0), 700, 500);
        loginFrame.setBounds( (0), (0), 700, 500);
        mapFrame.setBounds( (0), (0), 700, 500);
        this.setBounds(0, 0,700,500);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginFrame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        inputUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        cancle2 = new javax.swing.JButton();
        registerFrame = new javax.swing.JFrame();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jCheckSmall = new javax.swing.JCheckBox();
        jCheckLong = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        registerUserID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        registerPassword = new javax.swing.JPasswordField();
        registerRePassword = new javax.swing.JPasswordField();
        bCreat = new javax.swing.JButton();
        cancle = new javax.swing.JButton();
        mapFrame = new javax.swing.JFrame();
        bLogoutMap = new javax.swing.JButton();
        massageFrame = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        SmallCarButtom = new javax.swing.JButton();
        LongCarButtom = new javax.swing.JButton();
        bLogin = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();
        bRegister = new javax.swing.JButton();

        jLabel1.setText("UserName:");

        inputUser.setText("Input user name");
        inputUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUserActionPerformed(evt);
            }
        });

        jLabel2.setText("Password:");

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cancle2.setText("Cancle");
        cancle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancle2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout loginFrameLayout = new org.jdesktop.layout.GroupLayout(loginFrame.getContentPane());
        loginFrame.getContentPane().setLayout(loginFrameLayout);
        loginFrameLayout.setHorizontalGroup(
            loginFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(loginFrameLayout.createSequentialGroup()
                .add(197, 197, 197)
                .add(loginFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(cancle2)
                    .add(jButton2)
                    .add(loginFrameLayout.createSequentialGroup()
                        .add(loginFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2))
                        .add(33, 33, 33)
                        .add(loginFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(inputPassword)
                            .add(inputUser, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        loginFrameLayout.setVerticalGroup(
            loginFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(loginFrameLayout.createSequentialGroup()
                .add(95, 95, 95)
                .add(loginFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(inputUser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(12, 12, 12)
                .add(loginFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(inputPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(30, 30, 30)
                .add(jButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(cancle2)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jCheckSmall.setText("Small Car");

        jCheckLong.setText("Long Car");

        jLabel12.setText("User ID:");

        jLabel14.setText("Re-type Password:");

        jLabel13.setText("Password:");

        bCreat.setText("Creat New Account");
        bCreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCreatActionPerformed(evt);
            }
        });

        cancle.setText("Cancle");
        cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout registerFrameLayout = new org.jdesktop.layout.GroupLayout(registerFrame.getContentPane());
        registerFrame.getContentPane().setLayout(registerFrameLayout);
        registerFrameLayout.setHorizontalGroup(
            registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, registerFrameLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel13)
                    .add(jLabel12)
                    .add(jLabel14))
                .add(69, 69, 69)
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(registerUserID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 207, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(registerPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 207, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(registerRePassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 215, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(285, 285, 285))
            .add(registerFrameLayout.createSequentialGroup()
                .add(397, 397, 397)
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jCheckSmall)
                    .add(jCheckLong))
                .add(0, 0, Short.MAX_VALUE))
            .add(registerFrameLayout.createSequentialGroup()
                .add(125, 125, 125)
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 541, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 541, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 531, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(cancle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, bCreat)))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        registerFrameLayout.setVerticalGroup(
            registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, registerFrameLayout.createSequentialGroup()
                .add(63, 63, 63)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(registerUserID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel12))
                .add(23, 23, 23)
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(registerPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(registerRePassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(registerFrameLayout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jCheckLong)
                        .add(18, 18, 18)
                        .add(jCheckSmall))
                    .add(registerFrameLayout.createSequentialGroup()
                        .add(84, 84, 84)
                        .add(bCreat)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cancle)
                .add(6, 6, 6)
                .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        bLogoutMap.setText("Logout");
        bLogoutMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutMapActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout mapFrameLayout = new org.jdesktop.layout.GroupLayout(mapFrame.getContentPane());
        mapFrame.getContentPane().setLayout(mapFrameLayout);
        mapFrameLayout.setHorizontalGroup(
            mapFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, mapFrameLayout.createSequentialGroup()
                .addContainerGap(312, Short.MAX_VALUE)
                .add(bLogoutMap))
        );
        mapFrameLayout.setVerticalGroup(
            mapFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mapFrameLayout.createSequentialGroup()
                .add(bLogoutMap)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout massageFrameLayout = new org.jdesktop.layout.GroupLayout(massageFrame.getContentPane());
        massageFrame.getContentPane().setLayout(massageFrameLayout);
        massageFrameLayout.setHorizontalGroup(
            massageFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(massageFrameLayout.createSequentialGroup()
                .add(155, 155, 155)
                .add(jButton1)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        massageFrameLayout.setVerticalGroup(
            massageFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(massageFrameLayout.createSequentialGroup()
                .add(129, 129, 129)
                .add(jButton1)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SmallCarButtom.setText("Small Cars");
        SmallCarButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallCarButtomActionPerformed(evt);
            }
        });

        LongCarButtom.setText("Long Cars");
        LongCarButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LongCarButtomActionPerformed(evt);
            }
        });

        bLogin.setText("LogIn");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        bLogout.setText("LogOut");

        bRegister.setText("Register");
        bRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegisterActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(144, 144, 144)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(LongCarButtom, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(SmallCarButtom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 248, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(274, 274, 274))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(bRegister)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(bLogin)
                .add(18, 18, 18)
                .add(bLogout)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bLogout)
                    .add(bLogin)
                    .add(bRegister))
                .add(62, 62, 62)
                .add(SmallCarButtom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(73, 73, 73)
                .add(LongCarButtom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LongCarButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LongCarButtomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LongCarButtomActionPerformed

    private void SmallCarButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallCarButtomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SmallCarButtomActionPerformed

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        loginFrame.setVisible(true);
    }//GEN-LAST:event_bLoginActionPerformed

    private void bLogoutMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutMapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLogoutMapActionPerformed

    private void inputUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUserActionPerformed

    private void bRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegisterActionPerformed
        // TODO add your handling code here:
        registerUserID.setText("");
        registerPassword.setText("");
        registerRePassword.setText("");
        
        registerFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bRegisterActionPerformed

    public boolean inputComplete()
    {
        if (registerPassword.getText().equals("")){
            return false;
        }
        else if (registerUserID.getText().equals("")){
            return false;
        }
        else if (registerRePassword.getText().equals("")){
            return false;
        }
        else if (jCheckSmall.isSelected() && jCheckLong.isSelected()){
            return false;
        }
        else if (!jCheckSmall.isSelected() && !jCheckLong.isSelected()){
            return false;
        }
        else
            return true;
    }
    
    public boolean inputComplete2()
    {
        if (inputUser.getText().equals("")){
            return false;
        }
        else if (inputPassword.getText().equals("")){
            return false;
        }
        else
            return true;
    }
    
    private void bCreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreatActionPerformed
        // TODO add your handling code here:
        //System.out.print(inputComplete());
        boolean pass = true;
        if(inputComplete())
        {
            if(registerPassword.getText().equals(registerRePassword.getText())){
                if (member == 0)
                {
                }
                else{
                    for (int i = 0; i < member; i++)
                    {
                        //System.out.print(inputComplete());
                        if (user[i].getUserName() == registerUserID.getText())
                        {
                            //System.out.print(inputComplete());
                            pass = false;
                        }
                        /*else
                        {
                            //System.out.print(inputComplete());
                            if (jCheckSmall.isSelected()){
                                user[member] = new User(registerUserID.getText(), registerPassword.getText(), 'S');
                            }
                            else if (jCheckLong.isSelected()){
                                user[member] = new User(registerUserID.getText(), registerPassword.getText(), 'L');
                            }
                            member++;
                        }*/
                    }
                }
                if (pass){
                    if (jCheckSmall.isSelected()){
                        user[member] = new User(registerUserID.getText(), registerPassword.getText(), 'S');
                    }
                    else if (jCheckLong.isSelected()){
                        user[member] = new User(registerUserID.getText(), registerPassword.getText(), 'L');
                    }
                    member++;
                    registerFrame.setVisible(false);
                    this.setVisible(true);
                }
                    
            }
            
        }
        else{}
    }//GEN-LAST:event_bCreatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        massageFrame.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleActionPerformed
        // TODO add your handling code here:
        registerFrame.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_cancleActionPerformed

    private void cancle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancle2ActionPerformed
        // TODO add your handling code here:
        loginFrame.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_cancle2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        boolean pass = true;
        pass = false;
        if (inputComplete2()){
            if (member == 0){
                pass = false;
            }
            else{
                for (int i = 0; i < member; i++){
                    String name = inputUser.getText() + "";
                    String password = inputPassword.getText() + "";
                    if (login(user, member, name, password)){
                        pass = true;
                    }
                }
            }
            System.out.print(pass);
            if (pass){
                loginFrame.setVisible(false);
                mapFrame.setVisible(true);
            }
        }
        else{
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public boolean login(User user[], int member, String name, String password){
        for (int i = 0; i < member; i++){
            if (user[i].getUserName().equals(name) && user[i].getUserPassword().equals(password)){
                return true;
            }
        }
        return false;
    }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LongCarButtom;
    private javax.swing.JButton SmallCarButtom;
    private javax.swing.JButton bCreat;
    private javax.swing.JButton bLogin;
    private javax.swing.JButton bLogout;
    private javax.swing.JButton bLogoutMap;
    private javax.swing.JButton bRegister;
    private javax.swing.JButton cancle;
    private javax.swing.JButton cancle2;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckLong;
    private javax.swing.JCheckBox jCheckSmall;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JFrame loginFrame;
    private javax.swing.JFrame mapFrame;
    private javax.swing.JFrame massageFrame;
    private javax.swing.JFrame registerFrame;
    private javax.swing.JPasswordField registerPassword;
    private javax.swing.JPasswordField registerRePassword;
    private javax.swing.JTextField registerUserID;
    // End of variables declaration//GEN-END:variables

}
