/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserInterface.java
 *
 * Created on Dec 1, 2013, 8:38:52 PM
 */

package its;

/**
 *
 * @author Rogue
 */
import java.io.*;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

public class UserInterface extends javax.swing.JFrame {

    int MAX = 10;
    int member = 0;
    User[] user = new User[MAX];
    Login login;
    
    /** Creates new form UserInterface */
    public UserInterface() {
        initComponents();
        registerFrame.setBounds( (0), (0), 700, 500);
        loginFrame.setBounds( (0), (0), 700, 500);
        mapFrame.setBounds( (0), (0), 1000, 700);
        massageFrame.setBounds( (0), (0), 700, 500);
        this.setBounds(0, 0,700,500);
        p1.setText("Empty");
        p2.setText("Empty");
        p3.setText("Empty");
        p4.setText("Empty");
        p5.setText("Empty");
        p6.setText("Empty");
        p7.setText("Empty");
        p8.setText("Empty");
        p9.setText("Empty");
        p10.setText("Empty");
        p12.setText("Empty");
        p13.setText("Empty");
        p14.setText("Empty");
        p15.setText("Empty");
        p16.setText("Empty");
        p17.setText("Empty");
        p18.setText("Empty");
        p19.setText("Empty");
        p20.setText("Empty");
        p21.setText("Empty");
        p22.setText("Empty");
        p23.setText("Empty");
        p24.setText("Empty");

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginFrame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        inputUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        cancle2 = new javax.swing.JButton();
        registerFrame = new javax.swing.JFrame();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jCheckSmall = new javax.swing.JCheckBox();
        jCheckLong = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        registerUserID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        registerPassword = new javax.swing.JPasswordField();
        registerRePassword = new javax.swing.JPasswordField();
        bCreat = new javax.swing.JButton();
        cancle = new javax.swing.JButton();
        mapFrame = new javax.swing.JFrame();
        bLogoutMap = new javax.swing.JButton();
        p1 = new javax.swing.JButton();
        p2 = new javax.swing.JButton();
        p3 = new javax.swing.JButton();
        p4 = new javax.swing.JButton();
        p5 = new javax.swing.JButton();
        p6 = new javax.swing.JButton();
        p7 = new javax.swing.JButton();
        p8 = new javax.swing.JButton();
        p9 = new javax.swing.JButton();
        p10 = new javax.swing.JButton();
        p11 = new javax.swing.JButton();
        p12 = new javax.swing.JButton();
        p13 = new javax.swing.JButton();
        p14 = new javax.swing.JButton();
        p15 = new javax.swing.JButton();
        p16 = new javax.swing.JButton();
        p17 = new javax.swing.JButton();
        p18 = new javax.swing.JButton();
        p19 = new javax.swing.JButton();
        p20 = new javax.swing.JButton();
        p21 = new javax.swing.JButton();
        p22 = new javax.swing.JButton();
        p23 = new javax.swing.JButton();
        p24 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        massageFrame = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        SmallCarButtom = new javax.swing.JButton();
        LongCarButtom = new javax.swing.JButton();
        bLogin = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();
        bRegister = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setText("UserName:");

        inputUser.setText("Input user name");
        inputUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUserActionPerformed(evt);
            }
        });

        jLabel2.setText("Password:");

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cancle2.setText("Cancle");
        cancle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancle2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout loginFrameLayout = new org.jdesktop.layout.GroupLayout(loginFrame.getContentPane());
        loginFrame.getContentPane().setLayout(loginFrameLayout);
        loginFrameLayout.setHorizontalGroup(
            loginFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(loginFrameLayout.createSequentialGroup()
                .add(197, 197, 197)
                .add(loginFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(cancle2)
                    .add(jButton2)
                    .add(loginFrameLayout.createSequentialGroup()
                        .add(loginFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2))
                        .add(33, 33, 33)
                        .add(loginFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(inputPassword)
                            .add(inputUser, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        loginFrameLayout.setVerticalGroup(
            loginFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(loginFrameLayout.createSequentialGroup()
                .add(95, 95, 95)
                .add(loginFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(inputUser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(12, 12, 12)
                .add(loginFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(inputPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(30, 30, 30)
                .add(jButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(cancle2)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jCheckSmall.setText("Small Car");

        jCheckLong.setText("Long Car");

        jLabel12.setText("User ID:");

        jLabel14.setText("Re-type Password:");

        jLabel13.setText("Password:");

        bCreat.setText("Creat New Account");
        bCreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCreatActionPerformed(evt);
            }
        });

        cancle.setText("Cancle");
        cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout registerFrameLayout = new org.jdesktop.layout.GroupLayout(registerFrame.getContentPane());
        registerFrame.getContentPane().setLayout(registerFrameLayout);
        registerFrameLayout.setHorizontalGroup(
            registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, registerFrameLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel13)
                    .add(jLabel12)
                    .add(jLabel14))
                .add(69, 69, 69)
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(registerUserID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 207, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(registerPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 207, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(registerRePassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 215, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(285, 285, 285))
            .add(registerFrameLayout.createSequentialGroup()
                .add(397, 397, 397)
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jCheckSmall)
                    .add(jCheckLong))
                .add(0, 0, Short.MAX_VALUE))
            .add(registerFrameLayout.createSequentialGroup()
                .add(125, 125, 125)
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 541, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 541, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 531, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(cancle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, bCreat)))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        registerFrameLayout.setVerticalGroup(
            registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, registerFrameLayout.createSequentialGroup()
                .add(63, 63, 63)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(registerUserID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel12))
                .add(23, 23, 23)
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(registerPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(registerRePassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(registerFrameLayout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jCheckLong)
                        .add(18, 18, 18)
                        .add(jCheckSmall))
                    .add(registerFrameLayout.createSequentialGroup()
                        .add(84, 84, 84)
                        .add(bCreat)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cancle)
                .add(6, 6, 6)
                .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        bLogoutMap.setText("Logout");
        bLogoutMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutMapActionPerformed(evt);
            }
        });

        p1.setText("Empty");
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });

        p2.setText("Empty");
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });

        p3.setText("Empty");
        p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3ActionPerformed(evt);
            }
        });

        p4.setText("Empty");
        p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4ActionPerformed(evt);
            }
        });

        p5.setText("Empty");
        p5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5ActionPerformed(evt);
            }
        });

        p6.setText("Empty");
        p6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6ActionPerformed(evt);
            }
        });

        p7.setText("Empty");
        p7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p7ActionPerformed(evt);
            }
        });

        p8.setText("Empty");
        p8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p8ActionPerformed(evt);
            }
        });

        p9.setText("Empty");
        p9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p9ActionPerformed(evt);
            }
        });

        p10.setText("Empty");
        p10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p10ActionPerformed(evt);
            }
        });

        p11.setText("Empty");
        p11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p11ActionPerformed(evt);
            }
        });

        p12.setText("Empty");
        p12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p12ActionPerformed(evt);
            }
        });

        p13.setText("Empty");
        p13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p13ActionPerformed(evt);
            }
        });

        p14.setText("Empty");
        p14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p14ActionPerformed(evt);
            }
        });

        p15.setText("Empty");
        p15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p15ActionPerformed(evt);
            }
        });

        p16.setText("Empty");
        p16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p16ActionPerformed(evt);
            }
        });

        p17.setText("Empty");
        p17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p17ActionPerformed(evt);
            }
        });

        p18.setText("Empty");
        p18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p18ActionPerformed(evt);
            }
        });

        p19.setText("Empty");
        p19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p19ActionPerformed(evt);
            }
        });

        p20.setText("Empty");
        p20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p20ActionPerformed(evt);
            }
        });

        p21.setText("Empty");
        p21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p21ActionPerformed(evt);
            }
        });

        p22.setText("Empty");
        p22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p22ActionPerformed(evt);
            }
        });

        p23.setText("Empty");
        p23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p23ActionPerformed(evt);
            }
        });

        p24.setText("Empty");
        p24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p24ActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter");

        jLabel5.setText("Exit");

        org.jdesktop.layout.GroupLayout mapFrameLayout = new org.jdesktop.layout.GroupLayout(mapFrame.getContentPane());
        mapFrame.getContentPane().setLayout(mapFrameLayout);
        mapFrameLayout.setHorizontalGroup(
            mapFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mapFrameLayout.createSequentialGroup()
                .add(27, 27, 27)
                .add(mapFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(mapFrameLayout.createSequentialGroup()
                        .add(p16)
                        .add(18, 18, 18)
                        .add(p17)
                        .add(18, 18, 18)
                        .add(p18)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(p19)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(p20)
                        .add(18, 18, 18)
                        .add(p21)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(mapFrameLayout.createSequentialGroup()
                        .add(mapFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(p10)
                            .add(p1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(mapFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(mapFrameLayout.createSequentialGroup()
                                .add(0, 0, Short.MAX_VALUE)
                                .add(bLogoutMap))
                            .add(mapFrameLayout.createSequentialGroup()
                                .add(mapFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(mapFrameLayout.createSequentialGroup()
                                        .add(p2)
                                        .add(18, 18, 18)
                                        .add(p3)
                                        .add(18, 18, 18)
                                        .add(p4))
                                    .add(mapFrameLayout.createSequentialGroup()
                                        .add(p11)
                                        .add(18, 18, 18)
                                        .add(p12)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(mapFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(mapFrameLayout.createSequentialGroup()
                                        .add(p5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(p6))
                                    .add(p13))
                                .add(18, 18, 18)
                                .add(mapFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(mapFrameLayout.createSequentialGroup()
                                        .add(p7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(18, 18, 18)
                                        .add(p8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(18, 18, 18)
                                        .add(p9))
                                    .add(mapFrameLayout.createSequentialGroup()
                                        .add(mapFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(p14)
                                            .add(p22))
                                        .add(18, 18, 18)
                                        .add(mapFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(mapFrameLayout.createSequentialGroup()
                                                .add(p23)
                                                .add(18, 18, 18)
                                                .add(p24))
                                            .add(p15))))
                                .add(0, 104, Short.MAX_VALUE))))))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, mapFrameLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(mapFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel5)
                    .add(jLabel4))
                .add(24, 24, 24))
        );
        mapFrameLayout.setVerticalGroup(
            mapFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mapFrameLayout.createSequentialGroup()
                .add(mapFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(mapFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(p3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(p4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(p5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(p6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(p7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(p8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(p9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, mapFrameLayout.createSequentialGroup()
                        .add(bLogoutMap)
                        .add(18, 18, 18)
                        .add(mapFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(p2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(p1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .add(75, 75, 75)
                .add(jLabel4)
                .add(46, 46, 46)
                .add(mapFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(p10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .add(p11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(p12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(p13, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(p14, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(p15, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(45, 45, 45)
                .add(jLabel5)
                .add(64, 64, 64)
                .add(mapFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(p16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(p17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(p18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(p19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(p20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(p21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(p22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(p23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(p24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Your UserID is unvailable");

        org.jdesktop.layout.GroupLayout massageFrameLayout = new org.jdesktop.layout.GroupLayout(massageFrame.getContentPane());
        massageFrame.getContentPane().setLayout(massageFrameLayout);
        massageFrameLayout.setHorizontalGroup(
            massageFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(massageFrameLayout.createSequentialGroup()
                .add(massageFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(massageFrameLayout.createSequentialGroup()
                        .add(155, 155, 155)
                        .add(jButton1))
                    .add(massageFrameLayout.createSequentialGroup()
                        .add(121, 121, 121)
                        .add(jLabel3)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        massageFrameLayout.setVerticalGroup(
            massageFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(massageFrameLayout.createSequentialGroup()
                .add(104, 104, 104)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButton1)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SmallCarButtom.setText("Small Cars");
        SmallCarButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallCarButtomActionPerformed(evt);
            }
        });

        LongCarButtom.setText("Long Cars");
        LongCarButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LongCarButtomActionPerformed(evt);
            }
        });

        bLogin.setText("LogIn");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        bLogout.setText("LogOut");

        bRegister.setText("Register");
        bRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegisterActionPerformed(evt);
            }
        });

        jButton3.setText("Google Map");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(144, 144, 144)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(LongCarButtom, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(SmallCarButtom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 248, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(274, 274, 274))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(bRegister)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(bLogin)
                .add(18, 18, 18)
                .add(bLogout)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(229, 229, 229)
                .add(jButton3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bLogout)
                    .add(bLogin)
                    .add(bRegister))
                .add(62, 62, 62)
                .add(SmallCarButtom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(73, 73, 73)
                .add(LongCarButtom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 61, Short.MAX_VALUE)
                .add(jButton3)
                .add(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LongCarButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LongCarButtomActionPerformed
        // TODO add your handling code here:

        p1.setText("Empty");
        p2.setText("Empty");
        p3.setText("Empty");
        p4.setText("Empty");
        p5.setText("Empty");
        p6.setText("Empty");
        p7.setText("Empty");
        p8.setText("Empty");
        p9.setText("Empty");
        p10.setText("Empty");
        p12.setText("Empty");
        p13.setText("Empty");
        p14.setText("Empty");
        p15.setText("Empty");
        p16.setText("Empty");
        p17.setText("Empty");
        p18.setText("Empty");
        p19.setText("Empty");
        p20.setText("Empty");
        p21.setText("Empty");
        p22.setText("Empty");
        p23.setText("Empty");
        p24.setText("Empty");
        
        p1.setEnabled(true);
        p2.setEnabled(true);
        p3.setEnabled(true);
        p4.setEnabled(true);
        p5.setEnabled(true);
        p6.setEnabled(true);
        p7.setEnabled(true);
        p8.setEnabled(true);
        p9.setEnabled(true);
        p10.setEnabled(true);
        p11.setEnabled(true);
        p12.setEnabled(true);
        p13.setEnabled(true);
        p14.setEnabled(true);
        p15.setEnabled(true);
        p16.setEnabled(true);
        p17.setEnabled(true);
        p18.setEnabled(true);
        p19.setEnabled(true);
        p20.setEnabled(true);
        p21.setEnabled(true);
        p22.setEnabled(true);
        p23.setEnabled(true);
        p24.setEnabled(true);
        
        
        this.setVisible(false);
        mapFrame.setVisible(true);
        int num = 0;
        num = (int)(Math.random() * 23 + 1);
        for (int i = 0; i < num; i++){
            int occupied = (int)(Math.random() * 23 + 1);
            if (occupied == 1){
                p1.setText("Occupied");
                p1.setEnabled(false);
            }
            else if (occupied == 2){
                p2.setText("Occupied");
                p2.setEnabled(false);
            }
            else if (occupied == 3){
                p3.setText("Occupied");
                p3.setEnabled(false);
            }
            else if (occupied == 4){
                p4.setText("Occupied");
                p4.setEnabled(false);
            }
            else if (occupied == 5){
                p5.setText("Occupied");
                p5.setEnabled(false);
            }
            else if (occupied == 6){
                p6.setText("Occupied");
                p6.setEnabled(false);
            }
            else if (occupied == 7){
                p7.setText("Occupied");
                p7.setEnabled(false);
            }
            else if (occupied == 8){
                p8.setText("Occupied");
                p8.setEnabled(false);
            }
            else if (occupied == 9){
                p9.setText("Occupied");
                p9.setEnabled(false);
            }
            else if (occupied == 10){
                p10.setText("Occupied");
                p10.setEnabled(false);
            }
            else if (occupied == 11){
                p11.setText("Occupied");
                p11.setEnabled(false);
            }
            else if (occupied == 12){
                p12.setText("Occupied");
                p12.setEnabled(false);
            }
            else if (occupied == 13){
                p13.setText("Occupied");
                p13.setEnabled(false);
            }
            else if (occupied == 14){
                p14.setText("Occupied");
                p14.setEnabled(false);
            }
            else if (occupied == 15){
                p15.setText("Occupied");
                p15.setEnabled(false);
            }
            else if (occupied == 16){
                p16.setText("Occupied");
                p16.setEnabled(false);
            }
            else if (occupied == 17){
                p17.setText("Occupied");
                p17.setEnabled(false);
            }
            else if (occupied == 18){
                p18.setText("Occupied");
                p18.setEnabled(false);
            }
            else if (occupied == 19){
                p19.setText("Occupied");
                p19.setEnabled(false);
            }
            else if (occupied == 20){
                p20.setText("Occupied");
                p20.setEnabled(false);
            }
            else if (occupied == 21){
                p21.setText("Occupied");
                p21.setEnabled(false);
            }
            else if (occupied == 22){
                p22.setText("Occupied");
                p22.setEnabled(false);
            }
            else if (occupied == 23){
                p23.setText("Occupied");
                p23.setEnabled(false);
            }
            else if (occupied == 24){
                p24.setText("Occupied");
                p24.setEnabled(false);
            }
        }
    }//GEN-LAST:event_LongCarButtomActionPerformed

    private void SmallCarButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallCarButtomActionPerformed
        // TODO add your handling code here:
        
        p1.setText("Empty");
        p2.setText("Empty");
        p3.setText("Empty");
        p4.setText("Empty");
        p5.setText("Empty");
        p6.setText("Empty");
        p7.setText("Empty");
        p8.setText("Empty");
        p9.setText("Empty");
        p10.setText("Empty");
        p12.setText("Empty");
        p13.setText("Empty");
        p14.setText("Empty");
        p15.setText("Empty");
        p16.setText("Empty");
        p17.setText("Empty");
        p18.setText("Empty");
        p19.setText("Empty");
        p20.setText("Empty");
        p21.setText("Empty");
        p22.setText("Empty");
        p23.setText("Empty");
        p24.setText("Empty");
        
        p1.setEnabled(true);
        p2.setEnabled(true);
        p3.setEnabled(true);
        p4.setEnabled(true);
        p5.setEnabled(true);
        p6.setEnabled(true);
        p7.setEnabled(true);
        p8.setEnabled(true);
        p9.setEnabled(true);
        p10.setEnabled(true);
        p11.setEnabled(true);
        p12.setEnabled(true);
        p13.setEnabled(true);
        p14.setEnabled(true);
        p15.setEnabled(true);
        p16.setEnabled(true);
        p17.setEnabled(true);
        p18.setEnabled(true);
        p19.setEnabled(true);
        p20.setEnabled(true);
        p21.setEnabled(true);
        p22.setEnabled(true);
        p23.setEnabled(true);
        p24.setEnabled(true);
        
        this.setVisible(false);
        mapFrame.setVisible(true);
        int num = 0;
        num = (int)(Math.random() * 23 + 1);
        for (int i = 0; i < num; i++){
            int occupied = (int)(Math.random() * 23 + 1);
            if (occupied == 1){
                p1.setText("Occupied");
                p1.setEnabled(false);
            }
            else if (occupied == 2){
                p2.setText("Occupied");
                p2.setEnabled(false);
            }
            else if (occupied == 3){
                p3.setText("Occupied");
                p3.setEnabled(false);
            }
            else if (occupied == 4){
                p4.setText("Occupied");
                p4.setEnabled(false);
            }
            else if (occupied == 5){
                p5.setText("Occupied");
                p5.setEnabled(false);
            }
            else if (occupied == 6){
                p6.setText("Occupied");
                p6.setEnabled(false);
            }
            else if (occupied == 7){
                p7.setText("Occupied");
                p7.setEnabled(false);
            }
            else if (occupied == 8){
                p8.setText("Occupied");
                p8.setEnabled(false);
            }
            else if (occupied == 9){
                p9.setText("Occupied");
                p9.setEnabled(false);
            }
            else if (occupied == 10){
                p10.setText("Occupied");
                p10.setEnabled(false);
            }
            else if (occupied == 11){
                p11.setText("Occupied");
                p11.setEnabled(false);
            }
            else if (occupied == 12){
                p12.setText("Occupied");
                p12.setEnabled(false);
            }
            else if (occupied == 13){
                p13.setText("Occupied");
                p13.setEnabled(false);
            }
            else if (occupied == 14){
                p14.setText("Occupied");
                p14.setEnabled(false);
            }
            else if (occupied == 15){
                p15.setText("Occupied");
                p15.setEnabled(false);
            }
            else if (occupied == 16){
                p16.setText("Occupied");
                p16.setEnabled(false);
            }
            else if (occupied == 17){
                p17.setText("Occupied");
                p17.setEnabled(false);
            }
            else if (occupied == 18){
                p18.setText("Occupied");
                p18.setEnabled(false);
            }
            else if (occupied == 19){
                p19.setText("Occupied");
                p19.setEnabled(false);
            }
            else if (occupied == 20){
                p20.setText("Occupied");
                p20.setEnabled(false);
            }
            else if (occupied == 21){
                p21.setText("Occupied");
                p21.setEnabled(false);
            }
            else if (occupied == 22){
                p22.setText("Occupied");
                p22.setEnabled(false);
            }
            else if (occupied == 23){
                p23.setText("Occupied");
                p23.setEnabled(false);
            }
            else if (occupied == 24){
                p24.setText("Occupied");
                p24.setEnabled(false);
            }
            
        }
    }//GEN-LAST:event_SmallCarButtomActionPerformed

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
        inputUser.setText("User ID");
        inputPassword.setText("");
        
        this.setVisible(false);
        loginFrame.setVisible(true);
    }//GEN-LAST:event_bLoginActionPerformed

    private void bLogoutMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutMapActionPerformed
        // TODO add your handling code here:
        mapFrame.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_bLogoutMapActionPerformed

    private void inputUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUserActionPerformed

    private void bRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegisterActionPerformed
        // TODO add your handling code here:
        registerUserID.setText("");
        registerPassword.setText("");
        registerRePassword.setText("");
        
        registerFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bRegisterActionPerformed

    public boolean inputComplete()
    {
        if (registerPassword.getText().equals("")){
            return false;
        }
        else if (registerUserID.getText().equals("")){
            return false;
        }
        else if (registerRePassword.getText().equals("")){
            return false;
        }
        else if (jCheckSmall.isSelected() && jCheckLong.isSelected()){
            return false;
        }
        else if (!jCheckSmall.isSelected() && !jCheckLong.isSelected()){
            return false;
        }
        else
            return true;
    }
    
    public boolean inputComplete2()
    {
        if (inputUser.getText().equals("")){
            return false;
        }
        else if (inputPassword.getText().equals("")){
            return false;
        }
        else
            return true;
    }
    
    private void bCreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreatActionPerformed
        // TODO add your handling code here:
        //System.out.print(inputComplete());
        boolean pass = true;
        if(inputComplete())
        {
            if(registerPassword.getText().equals(registerRePassword.getText())){
                if (member == 0)
                {
                }
                else{
                    for (int i = 0; i < member; i++)
                    {
                        //System.out.print(inputComplete());
                        if (user[i].getUserName().equals(registerUserID.getText()))
                        {
                            //System.out.print(inputComplete());
                            pass = false;
                        }
                        
                    }
                }
                if (pass){
                    if (jCheckSmall.isSelected()){
                        user[member] = new User(registerUserID.getText(), registerPassword.getText(), 'S');
                    }
                    else if (jCheckLong.isSelected()){
                        user[member] = new User(registerUserID.getText(), registerPassword.getText(), 'L');
                    }
                    member++;
                    registerFrame.setVisible(false);
                    this.setVisible(true);
                }
                else{
                    massageFrame.setVisible(true);
                }
                    
            }
            
        }
        else{}
    }//GEN-LAST:event_bCreatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        massageFrame.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleActionPerformed
        // TODO add your handling code here:
        registerFrame.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_cancleActionPerformed

    private void cancle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancle2ActionPerformed
        // TODO add your handling code here:
        loginFrame.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_cancle2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        boolean pass = true;
        pass = false;
        if (inputComplete2()){
            if (member == 0){
                pass = false;
            }
            else{
                for (int i = 0; i < member; i++){
                    String name = inputUser.getText() + "";
                    String password = inputPassword.getText() + "";
                    if (login(user, member, name, password)){
                        pass = true;
                    }
                }
            }
            System.out.print(pass);
            if (pass){
                // TODO add your handling code here:
                int num = 0;
                num = (int)(Math.random() * 23 + 1);
                for (int i = 0; i < num; i++){
                    int occupied = (int)(Math.random() * 23 + 1);
                    if (occupied == 1){
                        p1.setText("Occupied");
                        p1.setEnabled(false);
                    }
                    else if (occupied == 2){
                        p2.setText("Occupied");
                        p2.setEnabled(false);
                    }
                    else if (occupied == 3){
                        p3.setText("Occupied");
                        p3.setEnabled(false);
                    }
                    else if (occupied == 4){
                        p4.setText("Occupied");
                        p4.setEnabled(false);
                    }
                    else if (occupied == 5){
                        p5.setText("Occupied");
                        p5.setEnabled(false);
                    }
                    else if (occupied == 6){
                        p6.setText("Occupied");
                        p6.setEnabled(false);
                    }
                    else if (occupied == 7){
                        p7.setText("Occupied");
                        p7.setEnabled(false);
                    }
                    else if (occupied == 8){
                        p8.setText("Occupied");
                        p8.setEnabled(false);
                    }
                    else if (occupied == 9){
                        p9.setText("Occupied");
                        p9.setEnabled(false);
                    }
                    else if (occupied == 10){
                        p10.setText("Occupied");
                        p10.setEnabled(false);
                    }
                    else if (occupied == 11){
                        p11.setText("Occupied");
                        p11.setEnabled(false);
                    }
                    else if (occupied == 12){
                        p12.setText("Occupied");
                        p12.setEnabled(false);
                    }
                    else if (occupied == 13){
                        p13.setText("Occupied");
                        p13.setEnabled(false);
                    }
                    else if (occupied == 14){
                        p14.setText("Occupied");
                        p14.setEnabled(false);
                    }
                    else if (occupied == 15){
                        p15.setText("Occupied");
                        p15.setEnabled(false);
                    }
                    else if (occupied == 16){
                        p16.setText("Occupied");
                        p16.setEnabled(false);
                    }
                    else if (occupied == 17){
                        p17.setText("Occupied");
                        p17.setEnabled(false);
                    }
                    else if (occupied == 18){
                        p18.setText("Occupied");
                        p18.setEnabled(false);
                    }
                    else if (occupied == 19){
                        p19.setText("Occupied");
                        p19.setEnabled(false);
                    }
                    else if (occupied == 20){
                        p20.setText("Occupied");
                        p20.setEnabled(false);
                    }
                    else if (occupied == 21){
                        p21.setText("Occupied");
                        p21.setEnabled(false);
                    }
                    else if (occupied == 22){
                        p22.setText("Occupied");
                        p22.setEnabled(false);
                    }
                    else if (occupied == 23){
                        p23.setText("Occupied");
                        p23.setEnabled(false);
                    }
                    else if (occupied == 24){
                        p24.setText("Occupied");
                        p24.setEnabled(false);
                    }
                }
                loginFrame.setVisible(false);
                mapFrame.setVisible(true);
            }
        }
        else{}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
        p2.setText("You");
    }//GEN-LAST:event_p2ActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
        p1.setText("You");
    }//GEN-LAST:event_p1ActionPerformed

    private void p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3ActionPerformed
        // TODO add your handling code here:
        p3.setText("You");
    }//GEN-LAST:event_p3ActionPerformed

    private void p4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4ActionPerformed
        // TODO add your handling code here:
        p4.setText("You");
    }//GEN-LAST:event_p4ActionPerformed

    private void p5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5ActionPerformed
        // TODO add your handling code here:
        p5.setText("You");
    }//GEN-LAST:event_p5ActionPerformed

    private void p6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6ActionPerformed
        // TODO add your handling code here:
        p6.setText("You");
    }//GEN-LAST:event_p6ActionPerformed

    private void p7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p7ActionPerformed
        // TODO add your handling code here:
        p7.setText("You");
    }//GEN-LAST:event_p7ActionPerformed

    private void p8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p8ActionPerformed
        // TODO add your handling code here:
        p8.setText("You");
    }//GEN-LAST:event_p8ActionPerformed

    private void p9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p9ActionPerformed
        // TODO add your handling code here:
        p9.setText("You");
    }//GEN-LAST:event_p9ActionPerformed

    private void p10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p10ActionPerformed
        // TODO add your handling code here:
        p10.setText("You");
    }//GEN-LAST:event_p10ActionPerformed

    private void p11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p11ActionPerformed
        // TODO add your handling code here:
        p11.setText("You");
    }//GEN-LAST:event_p11ActionPerformed

    private void p12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p12ActionPerformed
        // TODO add your handling code here:
        p12.setText("You");
    }//GEN-LAST:event_p12ActionPerformed

    private void p13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p13ActionPerformed
        // TODO add your handling code here:
        p13.setText("You");
    }//GEN-LAST:event_p13ActionPerformed

    private void p14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p14ActionPerformed
        // TODO add your handling code here:
        p14.setText("You");
    }//GEN-LAST:event_p14ActionPerformed

    private void p15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p15ActionPerformed
        // TODO add your handling code here:
        p15.setText("You");
    }//GEN-LAST:event_p15ActionPerformed

    private void p16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p16ActionPerformed
        // TODO add your handling code here:
        p16.setText("You");
    }//GEN-LAST:event_p16ActionPerformed

    private void p17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p17ActionPerformed
        // TODO add your handling code here:
        p17.setText("You");
    }//GEN-LAST:event_p17ActionPerformed

    private void p18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p18ActionPerformed
        // TODO add your handling code here:
        p18.setText("You");
    }//GEN-LAST:event_p18ActionPerformed

    private void p19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p19ActionPerformed
        // TODO add your handling code here:
        p19.setText("You");
    }//GEN-LAST:event_p19ActionPerformed

    private void p20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p20ActionPerformed
        // TODO add your handling code here:
        p10.setText("You");
    }//GEN-LAST:event_p20ActionPerformed

    private void p21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p21ActionPerformed
        // TODO add your handling code here:
        p21.setText("You");
    }//GEN-LAST:event_p21ActionPerformed

    private void p22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p22ActionPerformed
        // TODO add your handling code here:
        p22.setText("You");
    }//GEN-LAST:event_p22ActionPerformed

    private void p23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p23ActionPerformed
        // TODO add your handling code here:
        p23.setText("You");
    }//GEN-LAST:event_p23ActionPerformed

    private void p24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p24ActionPerformed
        // TODO add your handling code here:
        p24.setText("You");
    }//GEN-LAST:event_p24ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            String str = "cmd /c start iexplore https://maps.google.ca/maps?hl=en&tab=wl";
         try {

        Runtime.getRuntime().exec(str);

    } catch (IOException e) {

        e.printStackTrace();

    }
    try {

        URI uri = new URI("https://maps.google.ca/maps?hl=en&tab=wl");

        Desktop.getDesktop().browse(uri);

    } catch (URISyntaxException e) {

        e.printStackTrace();

    } catch (IOException e) {

        e.printStackTrace();

    }
    }//GEN-LAST:event_jButton3ActionPerformed

    public boolean login(User user[], int member, String name, String password){
        for (int i = 0; i < member; i++){
            if (user[i].getUserName().equals(name) && user[i].getUserPassword().equals(password)){
                return true;
            }
        }
        return false;
    }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LongCarButtom;
    private javax.swing.JButton SmallCarButtom;
    private javax.swing.JButton bCreat;
    private javax.swing.JButton bLogin;
    private javax.swing.JButton bLogout;
    private javax.swing.JButton bLogoutMap;
    private javax.swing.JButton bRegister;
    private javax.swing.JButton cancle;
    private javax.swing.JButton cancle2;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckLong;
    private javax.swing.JCheckBox jCheckSmall;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JFrame loginFrame;
    private javax.swing.JFrame mapFrame;
    private javax.swing.JFrame massageFrame;
    private javax.swing.JButton p1;
    private javax.swing.JButton p10;
    private javax.swing.JButton p11;
    private javax.swing.JButton p12;
    private javax.swing.JButton p13;
    private javax.swing.JButton p14;
    private javax.swing.JButton p15;
    private javax.swing.JButton p16;
    private javax.swing.JButton p17;
    private javax.swing.JButton p18;
    private javax.swing.JButton p19;
    private javax.swing.JButton p2;
    private javax.swing.JButton p20;
    private javax.swing.JButton p21;
    private javax.swing.JButton p22;
    private javax.swing.JButton p23;
    private javax.swing.JButton p24;
    private javax.swing.JButton p3;
    private javax.swing.JButton p4;
    private javax.swing.JButton p5;
    private javax.swing.JButton p6;
    private javax.swing.JButton p7;
    private javax.swing.JButton p8;
    private javax.swing.JButton p9;
    private javax.swing.JFrame registerFrame;
    private javax.swing.JPasswordField registerPassword;
    private javax.swing.JPasswordField registerRePassword;
    private javax.swing.JTextField registerUserID;
    // End of variables declaration//GEN-END:variables

}
