/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserInterface.java
 *
 * Created on Dec 1, 2013, 8:38:52 PM
 */

package its;

/**
 *
 * @author Rogue
 */
import java.io.*;
public class UserInterface extends javax.swing.JFrame {

    User[] user = new User[10];
    
    /** Creates new form UserInterface */
    public UserInterface() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginFram = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        inputUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        registerFrame = new javax.swing.JFrame();
        jSeparator2 = new javax.swing.JSeparator();
        lastNameBox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        firstNameBox = new javax.swing.JTextField();
        registerEmailBox = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        i3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        i4 = new javax.swing.JPasswordField();
        i5 = new javax.swing.JPasswordField();
        bCreat = new javax.swing.JButton();
        mapFram = new javax.swing.JFrame();
        bLogoutMap = new javax.swing.JButton();
        SmallCarButtom = new javax.swing.JButton();
        LongCarButtom = new javax.swing.JButton();
        bLogin = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();
        bRegister = new javax.swing.JButton();

        jLabel1.setText("UserName:");

        inputUser.setText("Input user name");
        inputUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUserActionPerformed(evt);
            }
        });

        jLabel2.setText("Password:");

        org.jdesktop.layout.GroupLayout loginFramLayout = new org.jdesktop.layout.GroupLayout(loginFram.getContentPane());
        loginFram.getContentPane().setLayout(loginFramLayout);
        loginFramLayout.setHorizontalGroup(
            loginFramLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(loginFramLayout.createSequentialGroup()
                .add(197, 197, 197)
                .add(loginFramLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel2))
                .add(33, 33, 33)
                .add(loginFramLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPasswordField)
                    .add(inputUser, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        loginFramLayout.setVerticalGroup(
            loginFramLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(loginFramLayout.createSequentialGroup()
                .add(95, 95, 95)
                .add(loginFramLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(inputUser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(12, 12, 12)
                .add(loginFramLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jPasswordField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        lastNameBox.setText("Last Name");

        jLabel7.setText("Name:");

        jLabel9.setText("Email Address:");

        firstNameBox.setText("First Name");
        firstNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameBoxActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Small Car");

        jCheckBox2.setText("Long Car");

        jLabel12.setText("User ID:");

        jLabel14.setText("Re-type Password:");

        jLabel13.setText("Password:");

        bCreat.setText("Creat New Account");
        bCreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCreatActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout registerFrameLayout = new org.jdesktop.layout.GroupLayout(registerFrame.getContentPane());
        registerFrame.getContentPane().setLayout(registerFrameLayout);
        registerFrameLayout.setHorizontalGroup(
            registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, registerFrameLayout.createSequentialGroup()
                .addContainerGap(422, Short.MAX_VALUE)
                .add(bCreat)
                .add(319, 319, 319))
            .add(registerFrameLayout.createSequentialGroup()
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(registerFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(registerFrameLayout.createSequentialGroup()
                                .add(88, 88, 88)
                                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel9)
                                    .add(jLabel7))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, registerFrameLayout.createSequentialGroup()
                                        .add(firstNameBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(lastNameBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, registerEmailBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 233, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jCheckBox1)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jCheckBox2)))
                            .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, registerFrameLayout.createSequentialGroup()
                                    .add(10, 10, 10)
                                    .add(jSeparator1))
                                .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 541, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(registerFrameLayout.createSequentialGroup()
                        .add(38, 38, 38)
                        .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 541, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(registerFrameLayout.createSequentialGroup()
                        .add(96, 96, 96)
                        .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(registerFrameLayout.createSequentialGroup()
                                .add(jLabel14)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(i5))
                            .add(registerFrameLayout.createSequentialGroup()
                                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel12)
                                    .add(jLabel13))
                                .add(54, 54, 54)
                                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(i4)
                                    .add(i3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 207, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        registerFrameLayout.setVerticalGroup(
            registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, registerFrameLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(lastNameBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(firstNameBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(registerEmailBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jCheckBox1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jCheckBox2)
                .add(8, 8, 8)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(27, 27, 27)
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(i3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(i4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(registerFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(i5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(25, 25, 25)
                .add(bCreat)
                .add(2, 2, 2)
                .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bLogoutMap.setText("Logout");
        bLogoutMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutMapActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout mapFramLayout = new org.jdesktop.layout.GroupLayout(mapFram.getContentPane());
        mapFram.getContentPane().setLayout(mapFramLayout);
        mapFramLayout.setHorizontalGroup(
            mapFramLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, mapFramLayout.createSequentialGroup()
                .addContainerGap(312, Short.MAX_VALUE)
                .add(bLogoutMap))
        );
        mapFramLayout.setVerticalGroup(
            mapFramLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mapFramLayout.createSequentialGroup()
                .add(bLogoutMap)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SmallCarButtom.setText("Small Cars");
        SmallCarButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallCarButtomActionPerformed(evt);
            }
        });

        LongCarButtom.setText("Long Cars");
        LongCarButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LongCarButtomActionPerformed(evt);
            }
        });

        bLogin.setText("LogIn");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        bLogout.setText("LogOut");

        bRegister.setText("Register");
        bRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegisterActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(144, 144, 144)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(LongCarButtom, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(SmallCarButtom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 248, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(274, 274, 274))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(bRegister)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(bLogin)
                .add(18, 18, 18)
                .add(bLogout)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bLogout)
                    .add(bLogin)
                    .add(bRegister))
                .add(62, 62, 62)
                .add(SmallCarButtom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(73, 73, 73)
                .add(LongCarButtom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LongCarButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LongCarButtomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LongCarButtomActionPerformed

    private void SmallCarButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallCarButtomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SmallCarButtomActionPerformed

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLoginActionPerformed

    private void bLogoutMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutMapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLogoutMapActionPerformed

    private void firstNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameBoxActionPerformed

    private void inputUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUserActionPerformed

    private void bRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegisterActionPerformed
        // TODO add your handling code here:
        registerFrame.setVisible(true);
        
    }//GEN-LAST:event_bRegisterActionPerformed

    private void bCreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreatActionPerformed
        // TODO add your handling code here:
        registerFrame.setVisible(false);
    }//GEN-LAST:event_bCreatActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LongCarButtom;
    private javax.swing.JButton SmallCarButtom;
    private javax.swing.JButton bCreat;
    private javax.swing.JButton bLogin;
    private javax.swing.JButton bLogout;
    private javax.swing.JButton bLogoutMap;
    private javax.swing.JButton bRegister;
    private javax.swing.JTextField firstNameBox;
    private javax.swing.JTextField i3;
    private javax.swing.JPasswordField i4;
    private javax.swing.JPasswordField i5;
    private javax.swing.JTextField inputUser;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField lastNameBox;
    private javax.swing.JFrame loginFram;
    private javax.swing.JFrame mapFram;
    private javax.swing.JTextField registerEmailBox;
    private javax.swing.JFrame registerFrame;
    // End of variables declaration//GEN-END:variables

}
